version: '2'
services:
  estoque-app:
    image: estoque
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://estoque-postgresql:5432/estoque'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://estoque-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://estoque-elasticsearch:9200'
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - 'KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_CONSUMER_GROUP_ID=estoque
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - 'KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - JHIPSTER_REGISTRY_PASSWORD=admin
  estoque-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=estoque
      - POSTGRES_PASSWORD=
  estoque-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  facturacao-app:
    image: facturacao
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://facturacao-postgresql:5432/facturacao'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://facturacao-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://facturacao-elasticsearch:9200'
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - 'KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_CONSUMER_GROUP_ID=facturacao
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - 'KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - JHIPSTER_REGISTRY_PASSWORD=admin
  facturacao-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=facturacao
      - POSTGRES_PASSWORD=
  facturacao-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://gateway-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://gateway-elasticsearch:9200'
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - 'KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_CONSUMER_GROUP_ID=gateway
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - 'KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
  gateway-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
  gateway-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  uaa-app:
    image: uaa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://uaa-postgresql:5432/uaa'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://uaa-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://uaa-elasticsearch:9200'
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - 'KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_CONSUMER_GROUP_ID=uaa
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - 'KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092'
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - JHIPSTER_REGISTRY_PASSWORD=admin
  uaa-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=uaa
      - POSTGRES_PASSWORD=
  uaa-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
